const settingsModule={async renderSettings(el){
  const get=async k=>(await db.settings.get(k))?.value||'';
  const [commission,subEnd,match,theme]=await Promise.all([get('commissionRate'),get('subscriptionEnd'),get('matchingWeights'),get('theme')]);
  const current=theme||localStorage.getItem('melkyar_theme')||'light';
  el.innerHTML=mk.page('تنظیمات','تنظیمات برنامه، ظاهر و کاربران','')+`<section class="panel"><h3>انتخاب تم برنامه</h3><div class="theme-grid">${[['light','روشن'],['emerald-gold','سبز و طلایی'],['sage','سبز ملایم'],['sand','کرم و طلایی']].map(([k,l])=>`<button type="button" class="theme-option ${current===k?'active':''}" data-theme="${k}">${l}</button>`).join('')}</div></section>
  <section class="panel"><h3>تنظیمات مالی و هوشمند</h3><div class="form-grid">${mk.input('درصد پیش‌فرض کمیسیون','commissionRate',commission||'1.5','number')}${mk.input('تاریخ پایان اشتراک','subscriptionEnd',subEnd,'date')}${mk.input('وزن‌های تطبیق (JSON)','matchingWeights',match||'{"area":25,"budget":30,"bedrooms":20,"amenities":25}')}<div class="hint">ایجاد کاربر جدید فقط توسط حساب سازنده برنامه انجام می‌شود.</div></div><button class="btn btn--primary" id="save-settings">ذخیره تنظیمات</button></section>
  <section class="panel"><div class="page-header"><div><h3>کاربران و دسترسی‌ها</h3><p class="muted">ایجاد کاربر جدید فقط توسط حساب سازنده انجام می‌شود.</p></div></div><div id="embedded-users"></div></section>
  <section class="panel"><h3>اطلاعات سازنده</h3><p>طراحی و ساخت توسط <strong>علیرضا بدر</strong></p><p>شرکت برنامه نویسی قو (سهامی خاص) — علیرضا بدر (Swanco)</p></section>`;
  el.querySelectorAll('[data-theme]').forEach(b=>b.onclick=async()=>{const t=b.dataset.theme;document.documentElement.setAttribute('data-theme',t);localStorage.setItem('melkyar_theme',t);for(const x of el.querySelectorAll('[data-theme]'))x.classList.toggle('active',x===b);const old=await db.settings.get('theme');old?await db.settings.update('theme',{value:t}):await db.settings.add({key:'theme',value:t});});
  el.querySelector('#save-settings').onclick=async()=>{const isOwner=!!(AUTH.currentUser()?.developer || AUTH.currentUser()?.username?.toLowerCase()==='alireza');const keys=['commissionRate','subscriptionEnd','matchingWeights'];for(const k of keys){const field=el.querySelector(`[name="${k}"]`);if(!field) continue;let v=field.value;const old=await db.settings.get(k);old?await db.settings.update(k,{value:v}):await db.settings.add({key:k,value:v});}ui.toast('تنظیمات ذخیره شد','success');};
  if(window.usersModule) await usersModule.renderUsers(el.querySelector('#embedded-users'),true);
}};window.settingsModule=settingsModule;