name = "melkyar-cloud"
compatibility_date = "2026-09-24"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "melkyar-db"
database_id = "9ed27b4d-c9d1-47ad-8edf-f3dc7c39e9dd"
